# Generated by Django 5.2 on 2025-04-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_bannerorvideo_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerorvideo',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='bannerorvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
