# Generated by Django 4.2.18 on 2025-01-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('levels', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_open_date', models.DateTimeField(blank=True, null=True)),
                ('registration_close_date', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_type', models.CharField(choices=[('tournament', 'Tournament'), ('competition', 'Competition')], default='competition', max_length=100)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='competition_banners/')),
                ('file_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('winning_price', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Winnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.register')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_rounds', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_open_date', models.DateTimeField(blank=True, null=True)),
                ('registration_close_date', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='tournament_banners/')),
                ('file_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('price', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('winning_price', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('competitions', models.ManyToManyField(related_name='tournaments', to='dashboard.competition')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('eliminated_percentage', models.PositiveIntegerField(default=20)),
                ('max_participants', models.PositiveIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='dashboard.competition')),
            ],
        ),
        migrations.CreateModel(
            name='PrizeBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Tournament', 'tournament'), ('Competition', 'competition')], default='Competition', max_length=20)),
                ('position', models.CharField(max_length=255)),
                ('prize', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.competition')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('sound', 'Sound'), ('music', 'Music')], max_length=10)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='competition_videos/')),
                ('sound_file', models.FileField(blank=True, null=True, upload_to='competition_sounds/')),
                ('music_file', models.FileField(blank=True, null=True, upload_to='competition_music/')),
                ('title', models.CharField(max_length=250)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dashboard.competition')),
            ],
        ),
    ]
