# Generated by Django 5.2 on 2025-04-29 05:22

import utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, storage=utils.helpers.AzureMediaStorage(), upload_to='competition_banners/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, storage=utils.helpers.AzureMediaStorage(), upload_to='tournament_banners/'),
        ),
    ]
