# Generated by Django 5.2 on 2025-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_competition_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='competition_banners/'),
        ),
    ]
