# Generated by Django 4.2.18 on 2025-01-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_register_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='referal_code',
        ),
        migrations.RemoveField(
            model_name='register',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='register',
            name='referral_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=100, unique=True)),
                ('date_referred', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='accounts.register')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='accounts.register')),
            ],
        ),
    ]
