# Generated by Django 4.2.18 on 2025-02-08 09:34

# from utils.helpers import AzureMediaStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_referralreward_amount'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='register',
        #     name='cover_image_url',
        #     field=models.CharField(blank=True, max_length=1000, null=True),
        # ),
        # migrations.AddField(
        #     model_name='register',
        #     name='profile_image_url',
        #     field=models.CharField(blank=True, max_length=1000, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='register',
        #     name='cover_image',
        #     field=models.ImageField(blank=True, null=True, storage=AzureMediaStorage(), upload_to='cover-images/'),
        # ),
        # migrations.AlterField(
        #     model_name='register',
        #     name='profile_image',
        #     field=models.ImageField(blank=True, null=True, storage=AzureMediaStorage(), upload_to='profile-images/'),
        # ),
    ]
