# Generated by Django 4.2.18 on 2025-02-10 11:19
# from utils.helpers import AzureMediaStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_register_cover_image_url_register_profile_image_url_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='awards',
        #     name='image_uri',
        #     field=models.CharField(blank=True, max_length=1000, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='awards',
        #     name='image',
        #     field=models.ImageField(storage=AzureMediaStorage(), upload_to='awards'),
        # ),
    ]
