# Generated by Django 5.2 on 2025-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_awards_image_uri_alter_awards_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='image',
            field=models.ImageField(upload_to='awards'),
        ),
    ]
