# Generated by Django 5.2 on 2025-04-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_awards_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover-images/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images/'),
        ),
    ]
