# Generated by Django 4.2.18 on 2025-01-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrelpaymenthistory',
            name='processed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
