# Generated by Django 4.2.18 on 2025-02-08 09:34

from django.db import migrations, models
# from utils.helpers import AzureMediaStorage


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='participant',
        #     name='file_uri',
        #     field=models.CharField(blank=True, max_length=500, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='participant',
        #     name='temp_video',
        #     field=models.FileField(blank=True, null=True, storage=AzureMediaStorage(), upload_to='competition_participants_temp_videos/'),
        # ),
        # migrations.AlterField(
        #     model_name='participant',
        #     name='video',
        #     field=models.FileField(blank=True, null=True, storage=AzureMediaStorage(), upload_to='competition_participants_videos/'),
        # ),
    ]
