# Generated by Django 5.2 on 2025-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_participant_temp_video_alter_participant_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='competition_participants_videos/'),
        ),
    ]
